baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Peter Arsenault Portfolio'
theme = "hugo-coder"

defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

[params]
author = "Peter Arsenault"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Peter Arsenault's personal website"
keywords = "blog,developer,personal"
info = ["Full Stack DevOps", "Technical Writer"]
avatarURL = "images/avatar.jpg"


[markup.highlight]
noClasses = false

[taxonomies]
series = "series"
tag = "tags"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"